### ISSUE TITLE
No storage available on CSS pods

### ISSUE THREAD

**Issue by angelo-v** [codecentric/web-clip#8]
CSS by default does not create profiles linking to an LDP storage. This leads to the error message `No storage available` for those users.

Check what is the correct way to find a storage on CSS and implement it. Alternatively provide a solution to enter a storage URL in the plugin options.

Resources:
- https://gitter.im/solid/specification?at=611a44153eec6d41d15c0c09
- https://github.com/solid/community-server/issues/910

**Comment by angelo-v** [comment]
Storage is now discovered during setup and can be manually adjusted

**Comment by bourgeoa** [comment]
You can't find storage by going up the folder tree until you find a container representation with a triple with `pim:Storage` as object.

**Comment by angelo-v** [comment]
> You can't find storage by going up the folder tree until you find a container representation with a triple with `pim:Storage` as object.

This is exactly what I am doing. If nothing is found the user has to provide an URL

**Comment by bourgeoa** [comment]
Sorry I put `can't` but should be `can`

Here is an example in https://bourgeoa.ga:3000/bourgeoa/ one of my CSS server
the same in https://bourgeoa.bourgeoa.ga:3000/

CSS does publish the pim:Storage in pod root container

```
@prefix dc: <http://purl.org/dc/terms/>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix posix: <http://www.w3.org/ns/posix/stat#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

<> a <http://www.w3.org/ns/pim/space#Storage>, ldp:Container, ldp:BasicContainer, ldp:Resource;
    dc:modified "2022-06-22T16:58:30.000Z"^^xsd:dateTime.
```
